services:
    jekyll:
        container_name: dev_mikehathaway_com
        network_mode: bridge
        restart: unless-stopped
        image: bretfisher/jekyll-serve
        volumes:
          - .:/site
        ports:
          - '4002:4000'
